alerts:
  email:
    enabled: true
    recipient_email: xxx@qq.com
    sender_email: xxx@qq.com
    sender_password: xxx
    smtp_port: 465
    smtp_server: smtp.qq.com
  telegram:
    bot_token: xxx
    chat_id: xxx
    enabled: true
monitoring:
  check_interval: 30
wechat:
  app_id:
  base_url: http://localhost:2531/v2/api
  callback_url: http://192.168.1.2:8069/callback
  token:
