ai_service:
  proxy_host: "http://xxx"
  default_provider: "openai"  # 默认使用的AI提供商
  providers:
    claude:
      models:
        Claude-3-Opus:
          model_id: "claude-3-opus-20240229"
          input_cost: 15.0
          output_cost: 75.0
        Claude-3-Sonnet:
          model_id: "claude-3-sonnet-20240229"
          input_cost: 3.0
          output_cost: 15.0
        Claude-3-Haiku:
          model_id: "claude-3-haiku-20240307"
          input_cost: 0.25
          output_cost: 1.25
      api_keys:
        active:
          - "your-claude-key-1"
          - "your-claude-key-2"
        exhausted: []
      api_version: "2023-06-01"
      default_model: "Claude-3-Sonnet"

    openai:
      models:
        GPT-4:
          model_id: "gpt-4"
          input_cost: 15.0
          output_cost: 60.0
        GPT-4o-mini:
          model_id: "gpt-4o-mini"
          input_cost: 0.15
          output_cost: 0.60
      api_keys:
        active:
          - "xxx"
          - "xxx"
        exhausted: []
      default_model: "GPT-4o-mini"